spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    parser:
      allow-single-quotes: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
server:
  port: 9091

mybatis:
  type-aliases-package: org.itachi.codestar.domain
  configuration:
    default-statement-timeout: 5
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

code:
  star:
    upload-file:

logging:
  level:
    org.itachi.codestar: DEBUG


---

spring:
  profiles: windows
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:c:/files/

code:
  star:
    upload-file: c:/files/uploads/

---

spring:
  profiles: mac
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/data1/files/

code:
  star:
    upload-file: /data1/files/uploads/

---

spring:
  profiles: local-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/erp??characterEncoding=utf-8&useUnicode=true
    username: erp
    password: My!erp2018